# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022 Scipp contributors (https://github.com/scipp)

name: nightly

on:
  push:
    branches:
      - main
      - release
  pull_request:

jobs:
  filewritersetup:
    name: Set up the file write, EFU and Kafka broker
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}  # required for conda env
    steps:

      - uses: actions/checkout@v3

      - name: Setup conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          micromamba-version: 0.23.0
          environment-file: environment.yml
          cache-env: true
          extra-specs: python=3.8

      - name: Cache conan setup
        id: conan-cache-key
        run: |
          echo "{key}={$(/bin/date -u "+%Y%m%d")}" >> $GITHUB_OUTPUT
          echo "{path}={$(conan config home)}" >> $GITHUB_OUTPUT

      - name: Cache conan
        uses: actions/cache@v1
        with:
          path: ${{ steps.conan-cache-key.outputs.path }}
          key: conan-${{ steps.conan-cache-key.outputs.key }}

      - run: bash ./setup.sh
